# Generated by Django 4.2.1 on 2023-06-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='main.customercar', verbose_name='Машина клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='main.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='customercar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_cars', related_query_name='customer_car', to='main.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='customercar',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_cars', related_query_name='customer_cars', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='car', to='main.brand', verbose_name='Марка'),
        ),
    ]
