# Generated by Django 4.2.1 on 2023-06-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterField(
            model_name='customercar',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Клиент'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cars', related_query_name='customer_cars', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='administrator',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Администратор'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Работник'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
